#!/usr/bin/env node
/**
 * build-tokens — emit the global CSS custom-property sheet the components read.
 *
 * Source of truth: tokens/primitive.json + tokens/semantic.json, authored in
 * W3C Design Tokens (DTCG) format (every leaf is `{ "$type", "$value" }`,
 * references are `{group.token}`). This flattens both into
 * `:root { --<group>-<path>: <value> }` so a component token like
 * `"{colors.foreground}"` resolves to `var(--colors-foreground)` at runtime.
 *
 * Run:  node scripts/build-tokens.mjs   →  writes src/tokens.css
 *
 * Nested composites (type recipes) flatten with `-` joins keeping their
 * original key casing (`--typography-page-title-fontFamily`), matching the
 * bridge in src/tokens.ts. Shadow tokens recompose to a CSS box-shadow string.
 * Internal `{group.token}` references are rewritten to `var(--group-token)`.
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const read = (p) => JSON.parse(readFileSync(join(root, p), 'utf8'))

const isPlainObject = (v) =>
  v !== null && typeof v === 'object' && !Array.isArray(v)
const isToken = (v) => isPlainObject(v) && '$value' in v

const deepMerge = (a, b) => {
  const out = { ...a }
  for (const [k, v] of Object.entries(b)) {
    out[k] =
      isPlainObject(v) && isPlainObject(out[k]) && !isToken(v) && !isToken(out[k])
        ? deepMerge(out[k], v)
        : v
  }
  return out
}

// `{colors.foreground}` → `var(--colors-foreground)`
const resolve = (value) =>
  String(value).replace(
    /\{([^}]+)\}/g,
    (_, ref) => `var(--${ref.replace(/\./g, '-')})`
  )

const shadowLayer = (s) =>
  [s.offsetX, s.offsetY, s.blur, s.spread, s.color].join(' ')
const shadowStr = (v) =>
  Array.isArray(v) ? v.map(shadowLayer).join(', ') : shadowLayer(v)

const emitLeaf = (name, token, out) => {
  const { $type: type, $value: value } = token
  if (type === 'shadow' || Array.isArray(value) || (isPlainObject(value) && 'offsetX' in value)) {
    out.push([name, shadowStr(value)])
  } else if (isPlainObject(value)) {
    // composite (typography recipe, etc.) — flatten sub-keys, keep casing.
    for (const [k, v] of Object.entries(value)) out.push([`${name}-${k}`, resolve(v)])
  } else {
    out.push([name, typeof value === 'string' ? resolve(value) : String(value)])
  }
}

const flatten = (prefix, obj, out) => {
  for (const [key, value] of Object.entries(obj)) {
    const name = `${prefix}-${key}`
    if (isToken(value)) emitLeaf(name, value, out)
    else if (isPlainObject(value)) flatten(name, value, out)
  }
}

// Merge sources per top-level group (semantic wins over primitive on shared keys).
const groups = {}
for (const src of [read('tokens/primitive.json'), read('tokens/semantic.json')]) {
  for (const [key, value] of Object.entries(src)) {
    groups[key] = deepMerge(groups[key] ?? {}, value)
  }
}

const vars = []
for (const [name, tree] of Object.entries(groups)) flatten(`--${name}`, tree, vars)

const css = `/* GENERATED by scripts/build-tokens.mjs — do not edit by hand. */
/* Source: tokens/primitive.json + tokens/semantic.json (DTCG format) */
:root {
${vars.map(([n, v]) => `  ${n}: ${v};`).join('\n')}
}
`

mkdirSync(join(root, 'src'), { recursive: true })
writeFileSync(join(root, 'src/tokens.css'), css)
console.log(`build-tokens: wrote src/tokens.css (${vars.length} custom properties)`)
